-- Add sequential order_number and support cash payments

-- Add order_number as an identity column for sequential, unique order numbers
ALTER TABLE public.orders
ADD COLUMN IF NOT EXISTS order_number BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- Backfill existing rows
UPDATE public.orders
SET order_number = DEFAULT
WHERE order_number IS NULL;

-- Ensure order_number is required and unique
ALTER TABLE public.orders
ALTER COLUMN order_number SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS orders_order_number_idx
ON public.orders(order_number);

-- Allow cash as a payment method while keeping existing values
ALTER TABLE public.orders
DROP CONSTRAINT IF EXISTS orders_payment_method_check;

ALTER TABLE public.orders
ALTER COLUMN payment_method SET DEFAULT 'card';

ALTER TABLE public.orders
ADD CONSTRAINT orders_payment_method_check
CHECK (payment_method IN ('card', 'cash', 'counter'));

-- Keep payment_status constraint but ensure it remains in place
ALTER TABLE public.orders
DROP CONSTRAINT IF EXISTS orders_payment_status_check;

ALTER TABLE public.orders
ADD CONSTRAINT orders_payment_status_check
CHECK (payment_status IN ('unpaid', 'paid', 'refund_pending', 'refunded'));
