// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wyqrolsmkwdwnahgkhfy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind5cXJvbHNta3dkd25haGdraGZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMzEyMDUsImV4cCI6MjA3MzcwNzIwNX0.gE-B10DVSs4yqCY2rAfc9d8R7OprszjKf-prmsFD3y0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});